docker-compose-yaml: docker-compose.yml

project: drupal8-example-simple

tasks:
#   pre-rollout:
#     - run:
#         name: drush sql-dump
#         command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
#         service: cli

  post-rollout:
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli



environments:
  cron-debug:
    monitoring_urls:
      - "www.haintzactuarial.com.au"
      - "haintzactuarial.com.au"
    routes:
      - nginx:
          - "1haintzactuarial.com.au":
              tls-acme: 'true'
              insecure: Redirect
              hsts: max-age=31536000
          - "1www.haintzactuarial.com.au":
              tls-acme: 'true'
              insecure: Redirect
              hsts: max-age=31536000
          - "1www.prod.haintzactuarial.com.au":
              tls-acme: 'true'
              insecure: Redirect
              hsts: max-age=31536000
          - "1prod.haintzactuarial.com.au":
              tls-acme: 'true'
              insecure: Redirect
              hsts: max-age=31536000
    cronjobs:
      - name: cronjob
        schedule: "*/15 * * * *"
        command: cd web && wp cron event run --due-now
        service: cli
      - name: clamav scan
        schedule: "15 1 * * *"
        command: |
          freshclam; \
          clamdscan --reload; \
          clamdscan /app/web/content/uploads/; \
          clamdscan /app/web/content/uploads/*/*; \
          clamdscan /app/web/content/uploads/*
        service: clamav
  master:
    routes:
      - nginx:
          - "www.uat.haintzactuarial.com.au":
              tls-acme: 'true'
              insecure: Redirect
              hsts: max-age=31536000
          - "uat.haintzactuarial.com.au":
              tls-acme: 'true'
              insecure: Redirect
